print("^7----------------------------------------------- ^7")
print("^7---------->>^8 RAR Store Not Working Now.. !! ^7")
print("^7----------------------------------------------- ^7")
         SetTimeout(5000,function ()
          StopResource(GetCurrentResourceName())
          StopResource("mysql-async")
          StopResource("vrp_mysql")
          StopResource("vrp")
          StopResource("spawnmanager")
          StopResource("mapmanager")
        end)
